/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_forma;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kandidat.Kandidat;

/**
 *
 * @author NEVEN
 */
public class forma extends javax.swing.JFrame {

    /**
     * Creates new form forma
     */
    public forma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        formaKurs = new javax.swing.JFrame();
        jbtnNedelja1 = new javax.swing.JButton();
        jbtnNedelja2 = new javax.swing.JButton();
        jbtnNedelja3 = new javax.swing.JButton();
        jbtnNedelja4 = new javax.swing.JButton();
        jbtnNedelja5 = new javax.swing.JButton();
        jbtnNedelja6 = new javax.swing.JButton();
        jbtnNedelja7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jlblBrIndeksa = new javax.swing.JLabel();
        jlblimeIPrezime = new javax.swing.JLabel();
        jtxtBrIndeksa = new javax.swing.JTextField();
        jtxtimeIPrezime = new javax.swing.JTextField();
        jbtnPocni = new javax.swing.JButton();
        jbtnPrikazi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jbtnPocniKurs = new javax.swing.JButton();

        formaKurs.setTitle("Računarske mreže i telekomunikacije");
        formaKurs.setPreferredSize(new java.awt.Dimension(600, 600));
        formaKurs.setSize(new java.awt.Dimension(1000, 600));

        jbtnNedelja1.setText("Uvod");
        jbtnNedelja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNedelja1ActionPerformed(evt);
            }
        });

        jbtnNedelja2.setText("Aplikativni sloj");
        jbtnNedelja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNedelja2ActionPerformed(evt);
            }
        });

        jbtnNedelja3.setText("UDP i GBN");
        jbtnNedelja3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNedelja3ActionPerformed(evt);
            }
        });

        jbtnNedelja4.setText("TCP");
        jbtnNedelja4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNedelja4ActionPerformed(evt);
            }
        });

        jbtnNedelja5.setText("Kontrola zagušenja");
        jbtnNedelja5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNedelja5ActionPerformed(evt);
            }
        });

        jbtnNedelja6.setText("Mrežni sloj");
        jbtnNedelja6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNedelja6ActionPerformed(evt);
            }
        });

        jbtnNedelja7.setText("Ruter");
        jbtnNedelja7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNedelja7ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout formaKursLayout = new javax.swing.GroupLayout(formaKurs.getContentPane());
        formaKurs.getContentPane().setLayout(formaKursLayout);
        formaKursLayout.setHorizontalGroup(
            formaKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formaKursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(formaKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnNedelja7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNedelja6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNedelja5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNedelja4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNedelja3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNedelja2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnNedelja1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        formaKursLayout.setVerticalGroup(
            formaKursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formaKursLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbtnNedelja1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnNedelja2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnNedelja3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnNedelja4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnNedelja5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnNedelja6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnNedelja7)
                .addContainerGap(348, Short.MAX_VALUE))
            .addGroup(formaKursLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Računarske mreže i telekomunikacije");

        jlblBrIndeksa.setText("Broj indeksa:");

        jlblimeIPrezime.setText("Ime i prezime:");

        jtxtBrIndeksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBrIndeksaActionPerformed(evt);
            }
        });

        jbtnPocni.setText("Počni");
        jbtnPocni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPocniActionPerformed(evt);
            }
        });

        jbtnPrikazi.setText("Prikaži rezultate");
        jbtnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrikaziActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        jbtnPocniKurs.setText("Počni kurs");
        jbtnPocniKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPocniKursActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblBrIndeksa)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtBrIndeksa))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblimeIPrezime)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnPocni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtimeIPrezime))))
                .addGap(18, 18, 18)
                .addComponent(jbtnPocniKurs)
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBrIndeksa)
                    .addComponent(jtxtBrIndeksa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblimeIPrezime)
                    .addComponent(jtxtimeIPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jbtnPocni)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnPrikazi)
                    .addComponent(jbtnPocniKurs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPocniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPocniActionPerformed
       try{
              // BufferedReader pitanja=new BufferedReader(new FileReader("Poruke.txt"));
            PrintWriter datoteka=new PrintWriter(new BufferedWriter(new FileWriter("Kandidati.txt", true)));
           
            
            
            
        if(jtxtBrIndeksa.getText().equals("") || jtxtimeIPrezime.getText().equals("")){
            JOptionPane.showMessageDialog(jbtnPocni,
                "Sva polja moraju biti popunjena! ",
                "Greska",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Kandidat kandidat=new Kandidat();
        
        Object[] options = {"lako","srednje","tesko"};
        int tezina = JOptionPane.showOptionDialog(jbtnPocni,
    "izaberi tezinu: ",
    "tezina kviza",
    JOptionPane.DEFAULT_OPTION,
    JOptionPane.PLAIN_MESSAGE,
    null,
    options,
    null);
    Object odgovor= options[tezina];
        
         switch(odgovor.toString()){
             case "lako":
                 otvoriLakTest(kandidat);
                 kandidat.setNivo("lak");
                 break;
             case "srednje":
                 otvoriSrednjiTest(kandidat);
                 kandidat.setNivo("srednji");
                 break;
             case "tesko":
                 otvoriTezakTest(kandidat);
                 kandidat.setNivo("tezak");
                 break;
         }
                 
        String polozio="";
       if(kandidat.getBrTacnih()>=6){
           polozio="Jeste polozio";
           kandidat.setPolozio(true);
       }
       else{
           polozio="Nije polozio";
           kandidat.setPolozio(false);
       }
       
       JOptionPane.showMessageDialog(this,
    "Broj tacnih odgovora: "+kandidat.getBrTacnih()+"\nBroj netacnih odgovora: "
            +kandidat.getBrNetacnih()+"\n"+polozio,
    "Resenje",
    JOptionPane.PLAIN_MESSAGE);
       
       kandidat.setBrIndeksa((jtxtBrIndeksa.getText()));
       kandidat.setimeIPrezime((jtxtimeIPrezime.getText()));
       datoteka.println(kandidat.toString());
       datoteka.close();
       
       }catch(IOException | HeadlessException | NumberFormatException e){
          JOptionPane.showMessageDialog(null,
    "Greska pri upisivanju kandidata! ",
    "Greska",
    JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jbtnPocniActionPerformed

    private void jtxtBrIndeksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBrIndeksaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBrIndeksaActionPerformed

    private void jbtnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrikaziActionPerformed
        try{
            BufferedReader datoteka=new BufferedReader(new FileReader("Kandidati.txt"));
            boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea1.setText(tekst);
            datoteka.close();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,
    "Greska pri prikazivanju kandidata! ",
    "Greska",
    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnPrikaziActionPerformed

    private void jbtnPocniKursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPocniKursActionPerformed
        formaKurs.setVisible(true);
    }//GEN-LAST:event_jbtnPocniKursActionPerformed

    private void jbtnNedelja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNedelja1ActionPerformed
        try {
            BufferedReader datoteka=new BufferedReader(new FileReader("nedelja1.txt"));
             boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea2.setText(tekst);
            datoteka.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
            "Greska pri prikazivanju teksta! ",
            "Greska",
            JOptionPane.ERROR_MESSAGE);      
        }
    }//GEN-LAST:event_jbtnNedelja1ActionPerformed

    private void jbtnNedelja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNedelja2ActionPerformed
        try {
            BufferedReader datoteka=new BufferedReader(new FileReader("nedelja2.txt"));
             boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea2.setText(tekst);
            datoteka.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
            "Greska pri prikazivanju teksta! ",
            "Greska",
            JOptionPane.ERROR_MESSAGE);        
}  
    }//GEN-LAST:event_jbtnNedelja2ActionPerformed

    private void jbtnNedelja3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNedelja3ActionPerformed
        try {
            BufferedReader datoteka=new BufferedReader(new FileReader("nedelja3.txt"));
             boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea2.setText(tekst);
            datoteka.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
            "Greska pri prikazivanju teksta! ",
            "Greska",
            JOptionPane.ERROR_MESSAGE);        
}  
    }//GEN-LAST:event_jbtnNedelja3ActionPerformed

    private void jbtnNedelja4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNedelja4ActionPerformed
        try {
            BufferedReader datoteka=new BufferedReader(new FileReader("nedelja4.txt"));
             boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea2.setText(tekst);
            datoteka.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
            "Greska pri prikazivanju teksta! ",
            "Greska",
            JOptionPane.ERROR_MESSAGE);        
}  
    }//GEN-LAST:event_jbtnNedelja4ActionPerformed

    private void jbtnNedelja5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNedelja5ActionPerformed
        try {
            BufferedReader datoteka=new BufferedReader(new FileReader("nedelja5.txt"));
             boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea2.setText(tekst);
            datoteka.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
            "Greska pri prikazivanju teksta! ",
            "Greska",
            JOptionPane.ERROR_MESSAGE);        
}  
    }//GEN-LAST:event_jbtnNedelja5ActionPerformed

    private void jbtnNedelja6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNedelja6ActionPerformed
        try {
            BufferedReader datoteka=new BufferedReader(new FileReader("nedelja6.txt"));
             boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea2.setText(tekst);
            datoteka.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
            "Greska pri prikazivanju teksta! ",
            "Greska",
            JOptionPane.ERROR_MESSAGE);        
}  
    }//GEN-LAST:event_jbtnNedelja6ActionPerformed

    private void jbtnNedelja7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNedelja7ActionPerformed
        try {
            BufferedReader datoteka=new BufferedReader(new FileReader("nedelja7.txt"));
             boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea2.setText(tekst);
            datoteka.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null,
            "Greska pri prikazivanju teksta! ",
            "Greska",
            JOptionPane.ERROR_MESSAGE);        
}  
    }//GEN-LAST:event_jbtnNedelja7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forma().setVisible(true);
            }
        });
    }

    void otvoriLakTest(Kandidat kandidat){
        try{
         BufferedReader pitanja=new BufferedReader(new FileReader("PitanjaLak.txt"));
        Object[] options = {"tacno","netacno"}; 
        
        for(int brPitanja=1;brPitanja<=10;brPitanja++){ 
    int n = JOptionPane.showOptionDialog(jbtnPocni,
    pitanja.readLine()+"\n"+pitanja.readLine(),
    "Pitanje br: "+brPitanja,
    JOptionPane.DEFAULT_OPTION,
    JOptionPane.PLAIN_MESSAGE,
    null,
    options,
    null);
    Object odgovor= options[n];
    String tacanOdg=pitanja.readLine();
    
    
        if(odgovor.equals(tacanOdg)){
        JOptionPane.showMessageDialog(this,
    "Tacan odgovor! ",
    "Pitanje br: "+brPitanja,
    JOptionPane.PLAIN_MESSAGE);
   
        kandidat.setBrTacnih(kandidat.getBrTacnih()+1);
    }else{
        JOptionPane.showMessageDialog(this,
    "Netacan odgovor! ",
    "Pitanje br: "+brPitanja,
    JOptionPane.PLAIN_MESSAGE);
        
        kandidat.setBrNetacnih(kandidat.getBrNetacnih()+1);
    }
        }
    
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,
    "Greska pri pokretanju kviza! ",
    "Greska",
    JOptionPane.ERROR_MESSAGE);
    }
    }
    void otvoriSrednjiTest(Kandidat kandidat){
        try{
         BufferedReader pitanja=new BufferedReader(new FileReader("PitanjaSrednji.txt"));
        Object[] options = {"A","B","C","D","E"}; 
        
        for(int brPitanja=1;brPitanja<=10;brPitanja++){ 
    int n = JOptionPane.showOptionDialog(jbtnPocni,
    pitanja.readLine()+"\n"+pitanja.readLine(),
    "Pitanje br: "+brPitanja,
    JOptionPane.DEFAULT_OPTION,
    JOptionPane.PLAIN_MESSAGE,
    null,
    options,
    null);
    Object odgovor= options[n];
    String tacanOdg=pitanja.readLine();
    
    
        if(odgovor.equals(tacanOdg)){
        JOptionPane.showMessageDialog(this,
    "Tacan odgovor! ",
    "Pitanje br: "+brPitanja,
    JOptionPane.PLAIN_MESSAGE);
   
        kandidat.setBrTacnih(kandidat.getBrTacnih()+1);
    }else{
        JOptionPane.showMessageDialog(this,
    "Netacan odgovor! ",
    "Pitanje br: "+brPitanja,
    JOptionPane.PLAIN_MESSAGE);
        
        kandidat.setBrNetacnih(kandidat.getBrNetacnih()+1);
    }
        }
    
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,
    "Greska pri pokretanju kviza! ",
    "Greska",
    JOptionPane.ERROR_MESSAGE);
    }
    }
    
    void otvoriTezakTest(Kandidat kandidat){
        try{
         BufferedReader pitanja=new BufferedReader(new FileReader("PitanjaTezak.txt"));
        Object[] options = {"A","B","C","D","E","N"}; 
        
        for(int brPitanja=1;brPitanja<=10;brPitanja++){ 
    int n = JOptionPane.showOptionDialog(jbtnPocni,
    pitanja.readLine()+"\n"+pitanja.readLine(),
    "Pitanje br: "+brPitanja,
    JOptionPane.DEFAULT_OPTION,
    JOptionPane.PLAIN_MESSAGE,
    null,
    options,
    null);
    Object odgovor= options[n];
    String tacanOdg=pitanja.readLine();
    
    if(odgovor.equals("N")){
        continue;
    }else{
        if(odgovor.equals(tacanOdg)){
        JOptionPane.showMessageDialog(this,
    "Tacan odgovor! ",
    "Pitanje br: "+brPitanja,
    JOptionPane.PLAIN_MESSAGE);
   
        kandidat.setBrTacnih(kandidat.getBrTacnih()+1);
    }else{
        JOptionPane.showMessageDialog(this,
    "Netacan odgovor! ",
    "Pitanje br: "+brPitanja,
    JOptionPane.PLAIN_MESSAGE);
        
        kandidat.setBrNetacnih(kandidat.getBrNetacnih()+1);
    }
        }
       }
    
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,
    "Greska pri pokretanju kviza! ",
    "Greska",
    JOptionPane.ERROR_MESSAGE);
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame formaKurs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton jbtnNedelja1;
    private javax.swing.JButton jbtnNedelja2;
    private javax.swing.JButton jbtnNedelja3;
    private javax.swing.JButton jbtnNedelja4;
    private javax.swing.JButton jbtnNedelja5;
    private javax.swing.JButton jbtnNedelja6;
    private javax.swing.JButton jbtnNedelja7;
    private javax.swing.JButton jbtnPocni;
    private javax.swing.JButton jbtnPocniKurs;
    private javax.swing.JButton jbtnPrikazi;
    private javax.swing.JLabel jlblBrIndeksa;
    private javax.swing.JLabel jlblimeIPrezime;
    private javax.swing.JTextField jtxtBrIndeksa;
    private javax.swing.JTextField jtxtimeIPrezime;
    // End of variables declaration//GEN-END:variables
}
