/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui_forma;

import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import kandidat.Kandidat;

/**
 *
 * @author NEVEN
 */
public class forma extends javax.swing.JFrame {

    /**
     * Creates new form forma
     */
    public forma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblBrPrijave = new javax.swing.JLabel();
        jlblSifraZadatka = new javax.swing.JLabel();
        jtxtBrPrijave = new javax.swing.JTextField();
        jtxtSifraZadatka = new javax.swing.JTextField();
        jbtnPocni = new javax.swing.JButton();
        jbtnPrikazi = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblBrPrijave.setText("Broj prijave:");

        jlblSifraZadatka.setText("Sifra zadatka:");

        jtxtBrPrijave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBrPrijaveActionPerformed(evt);
            }
        });

        jbtnPocni.setText("Pocni");
        jbtnPocni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPocniActionPerformed(evt);
            }
        });

        jbtnPrikazi.setText("Prikazi rezultate");
        jbtnPrikazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrikaziActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblBrPrijave)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtBrPrijave))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblSifraZadatka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnPrikazi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnPocni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxtSifraZadatka))))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBrPrijave)
                    .addComponent(jtxtBrPrijave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSifraZadatka)
                    .addComponent(jtxtSifraZadatka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jbtnPocni)
                .addGap(37, 37, 37)
                .addComponent(jbtnPrikazi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnPocniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPocniActionPerformed
       try{
        PrintWriter datoteka=new PrintWriter(new BufferedWriter(new FileWriter("Kandidati.txt", true)));
        Object[] options = {"A","B","C","D","E","N"};
        Kandidat kandidat=new Kandidat();
       for(int brPitanja=1;brPitanja<=20;brPitanja++){
int n = JOptionPane.showOptionDialog(jbtnPocni,
    "Odgovor: ",
    "Pitanje br: "+brPitanja,
    JOptionPane.DEFAULT_OPTION,
    JOptionPane.PLAIN_MESSAGE,
    null,
    options,
    null);
    Object odgovor= options[n];
    kandidat.getResenja().add(odgovor);
        }
       kandidat.setBrPrijave((jtxtBrPrijave.getText()));
       kandidat.setSifraZadatka((jtxtSifraZadatka.getText()));
       datoteka.println(kandidat.toString());
       datoteka.close();
       }catch(IOException | HeadlessException | NumberFormatException e){
          JOptionPane.showMessageDialog(null,
    "Greska pri upisivanju kandidata! ",
    "Greska",
    JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_jbtnPocniActionPerformed

    private void jtxtBrPrijaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBrPrijaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBrPrijaveActionPerformed

    private void jbtnPrikaziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrikaziActionPerformed
        try{
            BufferedReader datoteka=new BufferedReader(new FileReader("Kandidati.txt"));
            boolean kraj=false;
            String tekst="";
            while(!kraj){
                String pom=datoteka.readLine();
                if(pom==null) kraj=true;
                else tekst=tekst+pom+"\n";
            }
            jTextArea1.setText(tekst);
            datoteka.close();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null,
    "Greska pri prikazivanju kandidata! ",
    "Greska",
    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnPrikaziActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbtnPocni;
    private javax.swing.JButton jbtnPrikazi;
    private javax.swing.JLabel jlblBrPrijave;
    private javax.swing.JLabel jlblSifraZadatka;
    private javax.swing.JTextField jtxtBrPrijave;
    private javax.swing.JTextField jtxtSifraZadatka;
    // End of variables declaration//GEN-END:variables
}
